= Accumulo Rolling Restart

In some situations an Accumulo admin will need to restart all Accumulo
processes in a cluster.  It would be nice if Accumulo supported a rolling
restart of its processes that minimized downtime of tablets.  This document
outlines a possible solution for
https://issues.apache.org/jira/browse/ACCUMULO-1454[ACCUMULO-1454]

Attempting a rolling restart with current versions of Accumulo causes a lot
unessecary tablet movement and loss of tablet locality.

== Use Cases

=== Configuration Requiring Restart

A configuration change is needed for Accumulo and/or Java that requires all
processes to be restarted.  This needs to be done while minimizing down time.
One possible way to achieve this is the following :

 . Make config change across cluster
 . On each worker node, do the following
 .. Disable tablet assignment
 .. Run stop-here.sh
 .. Run start-here.sh
 .. Enable tablet assignment
 .. Wait till all tablets are assigned

The Accumulo master assigns and balances tablets.  Assignment is done when an
tablet is not assigned to any tserver.  Balancing of tablets moves tablets
around and is only performed when all tablets are assigned.  Assignment is
disabled temporarily so that tablets are not assigned elsewhere for the brief
period that a tserver on a node is down.  When assignment is reenabled,
tablets will likely be assigned back to the same node.

Will this approach work well in the case where a user is running multiple
tablet servers per node?

=== Rolling upgrade

An upgrade from 1.7.0 to 1.7.1 is needed.  Would like to do this upgrade while
Accumulo is running inorder to minimize down time.  One possible way to achieve
this is the following :

 . Make config change across cluster
 . On each worker node, do the following
 .. Disable tablet assignment
 .. Run stop-here.sh in 1.7.0 directory
 .. Run start-here.sh in 1.7.1 directory
 .. Enable tablet assignment
 .. Wait till all tablets are assigned

Rolling upgrades are possible after https://issues.apache.org/jira/browse/ACCUMULO-751[ACCUMULO-751] 

== Behavioral change

In order to minimize the time any tablet is unavailable for read, stop-here.sh
could be modified to decommission a tablet server in the following way.

 . Hold all writes to the tablet server (except for metadata and root)
 . Start flushing each tablet.
 . Unload all tablets
 . Halt

While step 2 is running, all hosted tablets will be available for read.  Step 3
should be really quick as tablets will have no data to flush.  For bonus points
step 3 could be made super fast by batch writing tablet updates that occurr
during closing a tablet.   Alternatively, unloading tablets could be done in
parallel.  This would allow metadata updates to be committed to WAL in groups.
The faster step 3 goes, the less time tablets are unavailable for read.

== API Additions

=== Java API

[source,java]
----
public interface InstanceOperations{

  /** 
   * Disable tablet assignment. 
   */
  void disableAssignments();

  /**
   * Enable tablet assighment.
   */
  void enableAssignments();

  /**
   * Checks if automatic assignment of tablets is enabled.
   */
  boolean isAssignmentEnabled();

  /**
   * Decomissions a tablet server.  The tablet server will flush all data and
   * then kill itself.  While flushing data, a tablet server will stop
   * accepting writes and still accept reads. 
   */

   public void decomission(String tabletServer); // <1>

   /**
    * Waits for all tablets to be assigned.
    */
   public void waitForAssignments();

}
----

<1> Uncertain if this should be in API.  From the command line a user can run
`accumulo admin stop <tserver>`, but AFAIK this has no analouge in the Java
API.  So contemplating adding this method.

=== Shell Commands

....
assignments enable|disable|status|wait
decomission <tserver>  // <1>
....

<1> Would only add this, if it were added to API.

=== Proxy

TODO define proxy API after Java API settles

== Monitor

Accidently leaving assignment disabled could negatively impact system
stability.  The Accumulo monitor page should prominently show when its is
disabled.
